/* Generated by Yosys 0.9+3686 (git sha1 bc085761, clang  -fPIC -Os) */

module c17(N1, N2, N3, N6, N7, N22, N23);
  wire _0_;
  wire _1_;
  wire _2_;
  input N1;
  wire N11;
  wire N16;
  wire N19;
  input N2;
  output N22;
  output N23;
  input N3;
  input N6;
  input N7;
  sky130_fd_sc_hd__nand2_1 _3_ (
    .A(_0_),
    .B(N19),
    .Y(_1_)
  );
  sky130_fd_sc_hd__inv_1 _4_ (
    .A(_1_),
    .Y(_2_)
  );
  sky130_fd_sc_hd__nand2_2 _5_ (
    .A(_2_),
    .B(N16),
    .Y(N22)
  );
  sky130_fd_sc_hd__nand2_2 _6_ (
    .A(N3),
    .B(N6),
    .Y(N11)
  );
  sky130_fd_sc_hd__nand2_2 _7_ (
    .A(N11),
    .B(N2),
    .Y(N16)
  );
  sky130_fd_sc_hd__nand2_1 _8_ (
    .A(N1),
    .B(N3),
    .Y(_0_)
  );
  c18 NAND2_6 (
    .A0(N16),
    .A1(N19),
    .A2(N22),
    .A3(N23)
  );
  c18 SUB_0 (
    .A0(N11),
    .A1(N7),
    .A3(N19)
  );
endmodule

module c18(A3, A0, A1, A2);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input A0;
  input A1;
  input A2;
  output A3;
  sky130_fd_sc_hd__nand2_1 _4_ (
    .A(A1),
    .B(A2),
    .Y(_0_)
  );
  sky130_fd_sc_hd__inv_1 _5_ (
    .A(A0),
    .Y(_1_)
  );
  sky130_fd_sc_hd__nand2_1 _6_ (
    .A(_0_),
    .B(_1_),
    .Y(_2_)
  );
  sky130_fd_sc_hd__nand3_1 _7_ (
    .A(A1),
    .B(A2),
    .C(A0),
    .Y(_3_)
  );
  sky130_fd_sc_hd__nand2_1 _8_ (
    .A(_2_),
    .B(_3_),
    .Y(A3)
  );
endmodule
