# create image with runtime dependencies and a copy of the binary from a
# builder image
# NOTE: don't use this file directly unless you know what you are doing,
# instead use etc/DockerHelper.sh

# https://github.com/moby/moby/issues/38379#issuecomment-448445652
ARG copyImage=openroad/ubuntu22.04-builder:latest
ARG fromImage=openroad/ubuntu22.04-dev:latest

# need to use the line below as the "COPY --from" does not accept an ARG
FROM $copyImage AS copyfrom

FROM $fromImage

RUN apt-get -y update \
    && apt-get -y install --no-install-recommends \
      make \
      python3-flask \
      gunicorn \
      kicad

COPY --from=copyfrom /OpenROAD/build/bin/openroad /usr/bin/.
COPY --from=copyfrom /OpenROAD /opt/openroad

ADD https://github.com/utah-MFDA/openmfda_flow/archive/refs/heads/kicad.zip /opt/openmfda

# ENTRYPOINT [ "openroad" ]
